// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'employee_verification_data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_EmployeeVerificationDataModel _$EmployeeVerificationDataModelFromJson(
  Map<String, dynamic> json,
) => _EmployeeVerificationDataModel(
  employeeId: json['employeeId'] as String,
  staffId: json['staffId'] as String,
  firstName: json['firstName'] as String,
  fatherName: json['fatherName'] as String,
  grandName: json['grandName'] as String,
  fullName: json['fullName'] as String,
  gender: json['gender'] as String,
  birthDate: json['birthDate'] as String,
  photoUrl: json['photoUrl'] as String?,
  signature: json['signature'] as String?,
  motherName: json['motherName'] as String?,
  address: json['address'] as String?,
  appearance: json['appearance'] as String?,
  height: json['height'] as String?,
  mobile: json['mobile'] as String?,
  email: json['email'] as String?,
  bloodGroup: json['bloodGroup'] as String?,
  nationality: json['nationality'] as String?,
  religion: json['religion'] as String?,
  medicalStatus: json['medicalStatus'] as String?,
  retirementNumber: json['retirementNumber'] as String?,
  maritalStatus: json['maritalStatus'] as String?,
  isManager: json['isManager'] as bool?,
  bankAccount: json['bankAccount'] as String?,
  isRepresented: json['isRepresented'] as bool?,
  repBankAccount: json['repBankAccount'] as String?,
  entryBy: json['entryBy'] as String?,
  entryDate: json['entryDate'] as String?,
  employmentStatus: json['employmentStatus'] as String?,
  recuritmentType: json['recuritmentType'] as String?,
  employmentType: json['employmentType'] as String?,
  hiredDate: json['hiredDate'] as String?,
  retirementEligibilityDate: json['retirementEligibilityDate'] as String?,
  positionJoinedDate: json['positionJoinedDate'] as String?,
  employmentTerminationDate: json['employmentTerminationDate'] as String?,
  levelHoldingDate: json['levelHoldingDate'] as String?,
  scaleHoldingDate: json['scaleHoldingDate'] as String?,
  isCardIssued: json['isCardIssued'] as bool?,
  positionId: json['positionId'] as String?,
  positionName: json['positionName'] as String?,
  departmentId: json['departmentId'] as String?,
  departmentName: json['departmentName'] as String?,
  organizationId: json['organizationId'] as String?,
  organizationName: json['organizationName'] as String?,
  currentLevelId: json['currentLevelId'] as String?,
  levelName: json['levelName'] as String?,
  rankScaleId: json['rankScaleId'] as String?,
  scaleName: json['scaleName'] as String?,
  managerId: json['managerId'] as String?,
  managerName: json['managerName'] as String?,
);

Map<String, dynamic> _$EmployeeVerificationDataModelToJson(
  _EmployeeVerificationDataModel instance,
) => <String, dynamic>{
  'employeeId': instance.employeeId,
  'staffId': instance.staffId,
  'firstName': instance.firstName,
  'fatherName': instance.fatherName,
  'grandName': instance.grandName,
  'fullName': instance.fullName,
  'gender': instance.gender,
  'birthDate': instance.birthDate,
  'photoUrl': instance.photoUrl,
  'signature': instance.signature,
  'motherName': instance.motherName,
  'address': instance.address,
  'appearance': instance.appearance,
  'height': instance.height,
  'mobile': instance.mobile,
  'email': instance.email,
  'bloodGroup': instance.bloodGroup,
  'nationality': instance.nationality,
  'religion': instance.religion,
  'medicalStatus': instance.medicalStatus,
  'retirementNumber': instance.retirementNumber,
  'maritalStatus': instance.maritalStatus,
  'isManager': instance.isManager,
  'isRepresented': instance.isRepresented,
  'entryBy': instance.entryBy,
  'entryDate': instance.entryDate,
  'employmentStatus': instance.employmentStatus,
  'recuritmentType': instance.recuritmentType,
  'employmentType': instance.employmentType,
  'hiredDate': instance.hiredDate,
  'retirementEligibilityDate': instance.retirementEligibilityDate,
  'positionJoinedDate': instance.positionJoinedDate,
  'employmentTerminationDate': instance.employmentTerminationDate,
  'levelHoldingDate': instance.levelHoldingDate,
  'scaleHoldingDate': instance.scaleHoldingDate,
  'isCardIssued': instance.isCardIssued,
  'positionId': instance.positionId,
  'positionName': instance.positionName,
  'departmentId': instance.departmentId,
  'departmentName': instance.departmentName,
  'organizationId': instance.organizationId,
  'organizationName': instance.organizationName,
  'currentLevelId': instance.currentLevelId,
  'levelName': instance.levelName,
  'rankScaleId': instance.rankScaleId,
  'scaleName': instance.scaleName,
  'managerId': instance.managerId,
  'managerName': instance.managerName,
};
