// Describes various levels of educational attainment.
enum EducationLevel {
  elementarySchool,
  secondarySchoolFirstCycle,
  secondarySchoolSecondCycle,
  tvet,
  certificate,
  diploma,
  advancedDiploma,
  bachelorsDegree,
  bachelorsDegreeFiveYear,
  llbDegree,
  mdDegree,
  pharmDDegree,
  postgraduateDiploma,
  mastersDegree,
  mba,
  llm,
  specialtyCertificate,
  doctorOfMedicineSpecialty,
  phD,
  associateDegree,
  highSchoolDiploma,
  ged,
  other,
}