// Lists Ethiopian universities and higher education institutions.
enum EthiopianUniversity {
  addisAbabaUniversity,
  addisAbabaScienceAndTechnologyUniversity,
  adamaScienceAndTechnologyUniversity,
  bahirDarUniversity,
  mekelleUniversity,
  hawassaUniversity,
  arbaMinchUniversity,
  jimmaUniversity,
  haramayaUniversity,
  wollegaUniversity,
  debreMarkosUniversity,
  dillaUniversity,
  woldiaUniversity,
  maddaWalabuUniversity,
  wolaitaSodoUniversity,
  debreBirhanUniversity,
  gondarUniversity,
  direDawaUniversity,
  semeraUniversity,
  assosaUniversity,
  buleHoraUniversity,
  mizanTepiUniversity,
  jigjigaUniversity,
  amboUniversity,
  debreTaborUniversity,
  wachemoUniversity,
  bongaUniversity,
  metuUniversity,
  stMarysUniversity,
  unityUniversity,
  admasUniversity,
  riftValleyUniversity,
  ethiopianCivilServiceUniversity,
  alphaUniversity,
  newGenerationUniversity,
  keaMedUniversity,
  hiLCoE, // HiLCoE School of Computer Science and Technology
  americanCollegeOfTechnology,
  harmayaUniversityPrivate,
  jirenUniversity,
  bethelUniversity,
  axumUniversity,
  greenLandCollege,
  eiABC, // Ethiopian Institute of Architecture, Building Construction and City Development
  kotebeUniversityOfEducation,
  defenseUniversity,
  ethiopianPoliceUniversity,
  ethiopianAviationUniversity,
  ethiopianManagementInstitute,
  ethiopianFilmAcademy,
  other, // For "Other Institution"
}